// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMt0cxv8x2srm7smrceMm351Gk-fh9dTo',
    appId: '1:239704337423:web:b06cb465240190974d077a',
    messagingSenderId: '239704337423',
    projectId: 'deep-work-9cfdd',
    authDomain: 'deep-work-9cfdd.firebaseapp.com',
    storageBucket: 'deep-work-9cfdd.appspot.com',
    measurementId: 'G-M1VWX211H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ2GVNR9r8lHJSskDfVZf51JQG9am1yps',
    appId: '1:239704337423:android:98b2ee5a15c9958d4d077a',
    messagingSenderId: '239704337423',
    projectId: 'deep-work-9cfdd',
    storageBucket: 'deep-work-9cfdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgFdrfIssSh3mF-8V3m3FcEESGsXoosMo',
    appId: '1:239704337423:ios:8d7b7895855145bd4d077a',
    messagingSenderId: '239704337423',
    projectId: 'deep-work-9cfdd',
    storageBucket: 'deep-work-9cfdd.appspot.com',
    iosBundleId: 'com.example.deepWork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgFdrfIssSh3mF-8V3m3FcEESGsXoosMo',
    appId: '1:239704337423:ios:3c1aed3fbced6dbb4d077a',
    messagingSenderId: '239704337423',
    projectId: 'deep-work-9cfdd',
    storageBucket: 'deep-work-9cfdd.appspot.com',
    iosBundleId: 'com.example.deepWork.RunnerTests',
  );
}
